import {bits,hex} from './engine.js?v=2.8.3';
export const advancedCatalog={isa:['指令系统 · ISA 与寻址','CH04 / ISA','拆开指令字段，计算有效地址，追踪操作数与机器级控制流。'],control:['CPU · 控制信号与微操作','CH05 / CONTROL','单总线、暂存寄存器与控制字：一拍只做能同时完成的事。'],pipeline:['CPU · 流水线与冒险','CH05 / PIPELINE','逐周期观察指令重叠、暂停、转发与分支冲刷。'],interrupts:['I/O · 中断响应与屏蔽','CH07 / INTERRUPT','从请求判优、保存断点到服务和返回，区分响应与处理。']};
export const advancedDefaults={isaMode:'base',displacement:12,base:64,pcNext:34,isaTopic:'address',controlOp:'ADD',controller:'micro',pipelineCase:'load',forwarding:'on',interruptMask:0,interruptEnable:1};
const step=(title,note,active,values,extra={})=>({title,note,active,route:active,values,...extra});
export const demoMemory=a=>(a*3+7)&255;
export function addressResult(p){const a=p.displacement&255,r=p.base&255,signed=a<128?a:a-256;const mode=p.isaMode;const ea=mode==='direct'?a:mode==='indirect'?demoMemory(a):mode==='registerIndirect'?r:mode==='relative'?(p.pcNext+signed)&255:(r+(mode==='base'?signed:a))&255;return {ea:mode==='immediate'||mode==='register'?null:ea,value:mode==='immediate'?a:mode==='register'?r:demoMemory(ea),signed,pointer:mode==='indirect'?demoMemory(a):null};}
export function isaTrace(p){
 if(p.isaTopic==='call'){const rows=[['准备 CALL','PC=32，下一条地址34，SP=240；栈向低地址增长。','pc',32,240,'空'],['返回地址入栈','SP ← SP−2；M16[238] ← 34。保存的是返回地址，不是子程序入口。','stack',34,238,'[238]=34'],['跳入子程序','PC ← 100，开始执行函数。参数、局部量按约定存放。','pc',100,238,'[238]=34'],['执行函数体','示例函数把 R0=7 加一得到8；这里仅演示调用约定。','registers',102,238,'[238]=34'],['RET 弹出返回地址','PC ← M16[SP] = 34；SP ← SP+2。','stack',34,240,'已弹出'],['继续调用点之后','PC=34，SP恢复240，返回值R0=8。','pc',34,240,'空']];return rows.map(([title,note,id,pc,sp,stack],i)=>step(title,note,[id],{pc,sp,stack,R0:i>=3?8:7},{kind:'isa',fields:['CALL target','PCnext=34','target=100'],operation:note}));}
 if(p.isaTopic==='branch'){return [step('比较寄存器','CMP R0,3：R0=3，减法结果0，ZF=1。',['registers','alu'],{R0:3,ZF:1,pc:32}),step('解码条件跳转','BEQ +6 检查ZF，不直接检查寄存器中的十进制文本。',['ir','control'],{ZF:1,pc:32}),step('符号扩展与目标相加','本例偏移以字节计：PCnext=34，目标=34+6=40。',['alu','pc'],{ZF:1,pc:34,target:40}),step('选择下一条PC','ZF=1：PC←40；若ZF=0则PC←34。',['pc'],{ZF:1,pc:40})].map(f=>({...f,kind:'isa',fields:['BEQ','ZF=1','disp=+6'],operation:f.note}));}
 const r=addressResult(p),m=p.isaMode,labels={immediate:'立即',direct:'直接',indirect:'间接',register:'寄存器',registerIndirect:'寄存器间接',base:'基址',index:'变址',relative:'相对'};const formula=m==='immediate'?'操作数 = A':m==='register'?'操作数 = R':m==='direct'?'EA = A':m==='indirect'?'EA = M[A]':m==='registerIndirect'?'EA = R':m==='relative'?`EA = PCnext + sext(A) = ${p.pcNext} + (${r.signed})`:`EA = R + ${m==='base'?'sext(A)':'A'} = ${p.base} + (${m==='base'?r.signed:p.displacement})`;
 const values={mode:labels[m],A:p.displacement,R:p.base,EA:r.ea??'不需要',operand:r.value,pcNext:p.pcNext};const fields=['OP=LOAD','Rd=R0',`mode=${labels[m]}`,`A=${bits(p.displacement,8)}`];
 return [step('读出指令并划分字段','示例扩展ISA：OP、目标寄存器、寻址模式、8位地址/立即数字段。与原CPU程序页的16位ISA分开演示。',['pc','ir'],values),step('译码寻址方式',`${labels[m]}寻址；先区分地址字段A、有效地址EA和操作数。`,['ir','control'],values),step('选择地址形成输入',formula+'；本教学地址空间按8位回绕。',['registers','alu'],values),step(m==='indirect'?'先读取指针':'形成有效地址',m==='indirect'?`M[${p.displacement}]=${r.pointer}，它是地址，还不是最终操作数。`:r.ea===null?'立即数或寄存器直接供数，不访问数据主存。':`${formula} → EA=${r.ea}`,['alu','mar'],values),step('取得操作数',r.ea===null?`直接取得 ${r.value}。`:`读取 M[${r.ea}] = ${r.value}。本例内存 M[x]=(3x+7) mod256。`,r.ea===null?['registers']:['mar','memory','mdr'],values),step('写回目标寄存器',`R0 ← ${r.value}。直接、基址等访问一次数据主存；间接访问两次；立即和寄存器访问零次。不计取指。`,['mdr','registers'],values)].map(f=>({...f,kind:'isa',fields,operation:formula}));
}
export function controlTrace(p){const load=p.controlOp==='LOAD';const seq=[['PCout, MARin','PC → MAR','pc','mar',32],['Read, WMFC, MDRin','M[MAR] → MDR；等待访存完成','memory','mdr',load?0x2080:0x4001],['MDRout, IRin, PC+2','MDR → IR；专用增量器更新 PC','mdr','ir',load?0x2080:0x4001],['Decode','操作码译码并选择执行入口','ir','control',0],...(load? [['IRaddrOut, MARin','地址字段128 → MAR','ir','mar',128],['Read, WMFC, MDRin','M[128]=37 → MDR','memory','mdr',37],['MDRout, R0in','MDR → R0','mdr','registers',37]]:[['R0out, Yin','R0=7 → Y，锁存第一个操作数','registers','y',7],['R1out, ADD, Zin','总线上的R1=5与Y=7相加 → Z=12','alu','z',12],['Zout, R0in, FlagIn','Z → R0，并锁存标志','z','registers',12]]),['End','完成指令，下一微地址返回取指入口','control','pc',34]];return seq.map(([signals,op,a,b,value],i)=>step(`T${i} · ${op}`,`${p.controller==='micro'?'微程序：µPC寻址控制存储器，µIR输出控制字。':'硬布线：操作码、时序T与条件组合产生控制信号。'} ${op}。`,[a,b],{T:i,signals,bus:value,µPC:i,next:i===seq.length-1?0:i+1,R0:i>=6?(load?37:12):7,Y:i>=4&&!load?7:'—',Z:i>=5&&!load?12:'—'},{kind:'control',operation:op,signals:signals.split(', '),micro:p.controller==='micro',transfer:{from:a,to:b,value}}));}
export function pipelineTrace(p){
 const load=p.pipelineCase==='load',branch=p.pipelineCase==='branch',forward=p.forwarding==='on';
 const inst=branch?['BEQ R1,R1,L','ADD R2,R3,R4（错误路径）','SUB R5,R6,R7（错误路径）','L: ADD R8,R9,R10']:load?['LOAD R1,[R0]','ADD R2,R1,R3','SUB R4,R2,R5']:['ADD R1,R2,R3','SUB R4,R1,R5','ADD R6,R4,R7'];
 let schedules;
 if(branch)schedules=[['IF','ID','EX','MEM','WB'],['','IF','ID','FLUSH'],['','','IF','FLUSH'],['','','','IF','ID','EX','MEM','WB']];
 else{const stall1=forward?(load?1:0):2,stall2=forward?0:2;const ex1=3+stall1,ex2=ex1+1+stall2; schedules=[['IF','ID','EX','MEM','WB'],Array.from({length:ex1+3},(_,c)=>c===1?'IF':c>=2&&c<ex1?'ID / 等待':c===ex1?'EX':c===ex1+1?'MEM':c===ex1+2?'WB':''),Array.from({length:ex2+3},(_,c)=>c===2?'IF':c>2&&c<ex1?'IF / 保持':c>=ex1&&c<ex2?'ID / 等待':c===ex2?'EX':c===ex2+1?'MEM':c===ex2+2?'WB':'')];}
 const cycles=Math.max(...schedules.map(s=>s.length));return Array.from({length:cycles},(_,i)=>{const occupants=inst.map((name,j)=>({name,stage:schedules[j][i]??'',j}));const wait=occupants.some(x=>x.stage.includes('等待')||x.stage.includes('保持'));const flush=occupants.some(x=>x.stage==='FLUSH');const forwarded=!branch&&forward&&occupants.some(x=>x.j>0&&x.stage==='EX');const operation=flush?'分支成立：清空错误路径 IF/ID':wait?'RAW相关：冻结PC和IF/ID，EX插入气泡':forwarded?'选择转发输入：前条结果 → 当前ALU':'各级处理不同指令，级间寄存器在边沿锁存';return step(`周期 ${i+1} / ${cycles}`,`${operation}。五级 IF/ID/EX/MEM/WB；独立指令/数据存储器，写回可在同周期被ID读取。${load&&forward?'LOAD结果到MEM结束才可用，紧邻使用仍须停一拍。':''}`,occupants.filter(x=>['IF','ID','EX','MEM','WB'].includes(x.stage)).map(x=>x.stage),{cycle:i+1,forwarding:forward?'开启':'关闭',bubble:wait?'暂停':'无',cycles,CPI:(cycles/(branch?2:3)).toFixed(2)},{kind:'pipeline',occupants,inst,schedules,cycle:i,operation,forwarded,flush});});
}
export function interruptTrace(p){const blocked=!p.interruptEnable||p.interruptMask;const stages=blocked?[['请求到达','设备置IRQ=1，请求保持等待。','io'],['检查允许与屏蔽','IF=0或MASK=1，CPU不响应；请求不等于已进入服务。','control'],['继续主程序','保留待决请求。修改允许/屏蔽参数后重新演示响应路径。','pc']]:[['请求到达','设备就绪，IRQ置1；CPU先完成当前指令。','io'],['检查允许与判优','IF=1、MASK=0，选择请求并发出INTA。','control'],['保存断点和状态','硬件保存PCnext=34与PSW；SP从240降到236（各2字节）。','stack'],['关闭中断并查向量','IF←0；向量号2，向量表入口基址0+2×2=4。','vector'],['装入服务入口','M16[4]=160 → PC；转向中断服务程序。','pc'],['软件保存通用寄存器','服务程序PUSH R0；SP←234。硬件保存和软件保存不是同一步。','stack'],['读取数据与确认设备','RD访问数据端口0xF1，取得0x41；清设备请求。数据经CPU寄存器搬运。','io'],['恢复通用寄存器','POP R0，SP←236；准备中断返回。','stack'],['IRET 恢复状态与断点','恢复PSW（IF=1）与PC=34；SP←240。使用中断返回指令。','pc'],['返回主程序','继续被中断指令之后的下一条；本实验不模拟嵌套中断。','pc']];return stages.map(([title,note,id],i)=>step(title,note,[id],{IF:blocked?p.interruptEnable:i>=3&&i<8?0:1,MASK:p.interruptMask,IRQ:i<6?1:0,PC:!blocked&&i>=4&&i<8?160:34,SP:blocked?240:i>=5&&i<7?234:i>=2&&i<8?236:240,port:'0xF1',data:!blocked&&i>=6?'0x41':'—'},{kind:'interrupts',operation:note,blocked,route:blocked?[id]:[['io','control'],['control'],['pc','stack'],['control','vector'],['vector','pc'],['registers','stack'],['io','registers'],['stack','registers'],['stack','pc'],['pc']][i],stack:blocked||i<2||i>=8?[]:i>=5&&i<7?['R0（软件）','PSW（硬件）','PC=34（硬件）']:['PSW（硬件）','PC=34（硬件）']}));}
export const advancedTrace=(page,p)=>({isa:isaTrace,control:controlTrace,pipeline:pipelineTrace,interrupts:interruptTrace})[page](p);
