import {bits,multiplySteps,divideSteps} from './engine.js?v=2.8.3';
import {text,escape} from './textbook.js?v=2.8.3';
export function arithmeticMotion(page,p,f){const i=f.round;
 if(page==='adder'){const r=f.rows[i];return {operation:`FA${i}：${r.ai} + ${r.bi} + C${i}(${r.carry}) = ${r.ai+r.bi+r.carry}`,result:`S${i}=${r.sum}；C${i+1}=${r.next}`,rows:[{id:'a',name:'A · 选中当前位',before:p.a,after:p.a,n:8,selected:i},{id:'b',name:'B · 选中当前位',before:p.b,after:p.b,n:8,selected:i},{id:'sum',name:'S · 逐位写入',before:f.values.result&((1<<i)-1),after:f.values.result&((1<<(i+1))-1),n:8,selected:i,known:i+1}],token:String(r.ai+r.bi+r.carry),shift:false};}
 if(page==='multiplier'){const row=multiplySteps(p.a,p.b)[i],before=i?multiplySteps(p.a,p.b)[i-1].acc:0,m=p.a*2**i,q=p.b>>i;return {operation:f.phase===0?`选中 Q₀=${row.bit}：${row.bit?'下一步累加 M':'下一步保持 P'}`:f.phase===1?`${before} ${row.bit?'+ '+m:'+ 0（跳过）'} = ${row.acc}`:'M 逻辑左移 1 位；Q 逻辑右移 1 位',result:f.phase===2?'M低位补0；Q高位补0，旧Q₀移出':`P=${f.phase===0?before:row.acc}`,rows:[{id:'operand',name:'M · 被乘数',before:m,after:f.values.operand,n:16,shift:f.phase===2?-1:0},{id:'quotient',name:'Q · 乘数',before:q,after:f.values.quotient,n:8,selected:0,shift:f.phase===2?1:0},{id:'accumulator',name:'P · 部分积',before:f.phase===2?row.acc:before,after:f.values.accumulator,n:16}],token:f.phase===0?String(row.bit):String(row.acc),shift:f.phase===2};}
 const rows=divideSteps(p.a,p.b),r=rows[i],before=i?rows[i-1].remainder:0,bit=p.a>>(7-i)&1,shifted=before*2+bit,prevQ=i?rows[i-1].quotient:0;
 return {operation:f.phase===0?`R 左移1位，并移入 A${7-i}=${bit}`:f.phase===1?`${shifted} − ${p.b} = ${r.trial}（9位补码）`:r.take?`试减非负：保留 ${r.remainder}，写商1`:`试减为负：${r.trial} + ${p.b} = ${r.remainder}，写商0`,result:`本轮结束应满足 R=${r.remainder}，Q${7-i}=${+r.take}`,rows:[{id:'dividend',name:'A · 选中待移入位',before:p.a,after:p.a,n:8,selected:7-i},{id:'operand',name:'B · 除数',before:p.b,after:p.b,n:8},{id:'accumulator',name:'R · 余数/试减',before:f.phase===0?before:f.phase===1?shifted:r.trial,after:f.values.accumulator,n:9,shift:f.phase===0?-1:0,fill:bit},{id:'quotient',name:'Q · 写当前商位',before:prevQ,after:f.values.quotient,n:8,selected:7-i}],token:f.phase===0?String(bit):String(f.phase===1?r.trial:+r.take),shift:f.phase===0};
}
export function arithmeticMarkup(page,p,f){const m=arithmeticMotion(page,p,f),ys=[145,260,520,650];const rowMarkup=m.rows.map((r,j)=>{const x=300,y=ys[j],cw=36,w=r.n*cw;const before=bits(r.before,r.n),after=bits(r.after,r.n);return `<g class="arith-register" role="button" tabindex="0" data-register="${r.id}">${text(35,y+22,r.name,'tb-name')}${text(35,y+57,`${r.before} → ${r.after}`,'tb-small')}<defs><clipPath id="clip-${r.id}"><rect x="${x-1}" y="${y-2}" width="${w+2}" height="46"/></clipPath></defs>${Array.from(before,(b,k)=>{const selected=r.selected===r.n-1-k;return `<rect x="${x+k*cw}" y="${y}" width="${cw}" height="42" fill="${selected?'#ffe0a0':'#fff'}" stroke="${selected?'#b27618':'#7c9295'}" stroke-width="${selected?2.5:1}"/>${text(x+(k+.5)*cw,y-9,r.n-1-k,'arith-index','middle')}`;}).join('')}<g clip-path="url(#clip-${r.id})">${Array.from(before,(b,k)=>`<text x="${x+(k+.5)*cw}" y="${y+29}" text-anchor="middle" class="arith-digit" data-before="${r.known!==undefined&&r.n-1-k>=r.known-1?'?':b}" data-after="${r.known!==undefined&&r.n-1-k>=r.known?'?':after[k]}" data-shift="${r.shift??0}" data-bit="${r.n-1-k}">${b}</text>`).join('')}${r.shift?`<text x="${x+(r.shift<0?r.n-.5:.5)*cw}" y="${y+29}" text-anchor="middle" class="arith-fill" data-fill="1">${r.fill??0}</text>`:''}</g>${r.shift?text(x+w/2,y+76,r.shift<0?`← 每个数字移到高一位，右端补 ${r.fill??0}`:'每个数字移到低一位，左端补 0 →','tb-line-label','middle'):''}</g>`;}).join('');
 const tokenWidth=Math.max(52,m.token.length*15+20);
 const tokenX=page==='adder'?300+(7-f.round+.5)*36:page==='multiplier'?570:300+(f.round+.5)*36;
 const incoming=page==='divider'&&f.phase===0;
 const tokenY=page==='divider'&&f.phase===0?166:281;
 const tokenRoute=incoming?[[tokenX,tokenY],[tokenX,224],[940,224],[940,326],[505,326]]:[[tokenX,tokenY],[tokenX,326],[505,326]];
 const writeX=page==='adder'?300+(7-f.round+.5)*36:page==='divider'&&f.phase===2?300+(f.round+.5)*36:660,writeY=page==='divider'&&f.phase===2?670:540;
 return `<rect width="1000" height="820" fill="#fafbf6"/>${text(35,36,`${page==='adder'?'逐位加法':page==='multiplier'?'无符号移位相加':'恢复余数除法'} · 第 ${f.round+1} ${page==='adder'?'位（从最低位开始）':'轮'}`,'tb-heading')}${text(35,76,'金色：选中的数字　绿色：当前操作　单步也播放动画；可重播当前步','tb-small')}${rowMarkup}<path d="${tokenRoute.map(([x,y],i)=>`${i?'L':'M'}${x} ${y}`).join('')}V349M505 445V484H${writeX}V${writeY}" class="tb-wire control"/><rect x="180" y="350" width="750" height="95" rx="9" fill="#e8f5df" stroke="#41896d"/>${text(210,384,m.operation,'tb-note-title')}${text(210,420,m.result,'tb-small')}<g class="arith-token" data-route='${JSON.stringify(tokenRoute)}' data-x0="${tokenX}" data-y0="${tokenY}" data-x1="505" data-y1="326" data-bend="326"><rect x="${-tokenWidth/2}" y="-19" width="${tokenWidth}" height="38" rx="7" fill="#ffdd8b" stroke="#ad7a21"/>${text(0,7,m.token,'arith-digit','middle')}</g><g class="arith-write" data-x0="505" data-y0="468" data-x1="${writeX}" data-y1="${writeY}" data-bend="484" data-enabled="${page==='adder'||page==='multiplier'&&f.phase===1&&f.values.bit||page==='divider'&&f.phase>0?1:0}"><rect x="-56" y="-18" width="112" height="36" rx="6" fill="#bbebce"/>${text(0,7,page==='adder'?`写 S${f.round}`:page==='divider'&&f.phase===2?`写 Q${7-f.round}`:'写回','tb-name','middle')}</g>${page==='adder'?`<rect x="300" y="638" width="590" height="76" rx="8" fill="#fff2d4"/>${text(320,669,`C${f.round}=${f.rows[f.round].carry} → FA${f.round} → C${f.round+1}=${f.rows[f.round].next}`,'tb-note-title')}${text(320,701,f.round<7?`下一位 FA${f.round+1} 使用这条进位，不把它写进 S${f.round}`:'最高位完成：C₈用于无符号进位判断','tb-small')}`:''}${text(35,786,page==='adder'?'输入选位 → 求和 → Sᵢ 写入 → Cᵢ₊₁ 传给高位；未知和位暂用 ?':page==='multiplier'?'本页采用 M 左移、Q 右移；不混用 Booth 的算术右移。':'试减用9位补码；移位前后对照，同一轮最后才写入对应商位。','tb-small')}`;}
export function renderArithmetic(layer,t){const shiftT=Math.max(0,Math.min(1,(t-.2)/.55));for(const e of layer.querySelectorAll('.arith-digit[data-before]')){const shift=Number(e.dataset.shift);e.setAttribute('transform',shift&&t<.86?`translate(${shift*36*shiftT} 0)`:'');e.textContent=t<.86?e.dataset.before:e.dataset.after;}for(const e of layer.querySelectorAll('[data-fill]'))e.style.opacity=String(t>=.86?0:shiftT);for(const e of layer.querySelectorAll('.arith-token,.arith-write')){const write=e.classList.contains('arith-write'),u=Math.max(0,Math.min(1,(t-(write?.65:.05))/(write?.3:.4))),point=e.dataset.route?polylinePosition(JSON.parse(e.dataset.route),u):orthogonalPosition(Number(e.dataset.x0),Number(e.dataset.y0),Number(e.dataset.x1),Number(e.dataset.y1),Number(e.dataset.bend),u);e.setAttribute('transform',`translate(${point.x} ${point.y})`);e.style.opacity=write&&e.dataset.enabled==='0'||t<(write?.65:0)||t>(write?.98:.62)?'0':'1';}layer.setAttribute('data-animation-phase',t<.25?'select':t<.65?'operate':t<.86?'write':'complete');}

export function orthogonalPosition(x0,y0,x1,y1,bend,t){
 const lengths=[Math.abs(bend-y0),Math.abs(x1-x0),Math.abs(y1-bend)],points=[[x0,y0],[x0,bend],[x1,bend],[x1,y1]];let distance=Math.max(0,Math.min(1,t))*lengths.reduce((a,b)=>a+b,0);
 for(let i=0;i<3;i++){if(distance<=lengths[i]&&lengths[i]>0){const u=distance/lengths[i];return {x:points[i][0]+(points[i+1][0]-points[i][0])*u,y:points[i][1]+(points[i+1][1]-points[i][1])*u};}distance-=lengths[i];}return {x:x1,y:y1};
}

export function polylinePosition(points,t){
 const lengths=points.slice(1).map((p,i)=>Math.hypot(p[0]-points[i][0],p[1]-points[i][1]));let distance=Math.max(0,Math.min(1,t))*lengths.reduce((a,b)=>a+b,0);
 for(let i=0;i<lengths.length;i++){if(distance<=lengths[i]&&lengths[i]>0){const u=distance/lengths[i];return {x:points[i][0]+(points[i+1][0]-points[i][0])*u,y:points[i][1]+(points[i+1][1]-points[i][1])*u};}distance-=lengths[i];}const [x,y]=points.at(-1);return {x,y};
}
