export const hex=(n,w=4)=>'0x'+(n>>>0).toString(16).toUpperCase().padStart(w,'0');
export const bits=(n,w=8)=>(n>>>0).toString(2).padStart(w,'0').slice(-w);
export function add8(a,b,sub=false){a&=255;b&=255;const full=a+(sub?(~b&255):b)+(sub?1:0),value=full&255;return {value,CF:sub?+(a<b):+(full>255),OF:+(sub?!!((a^b)&(a^value)&128):!!((~(a^b))&(a^value)&128)),ZF:+(value===0),SF:value>>>7};}
export function multiplySteps(a,b){let acc=0;return Array.from({length:8},(_,i)=>{const bit=(b>>>i)&1,part=bit?(a&255)*2**i:0;acc+=part;return {i,bit,part,acc};});}
export function divideSteps(a,b){if(!b)throw Error('除数不能为 0');let remainder=0,quotient=0;return Array.from({length:8},(_,i)=>{remainder=remainder*2+((a>>>(7-i))&1);const trial=remainder-b;const take=trial>=0;if(take){remainder=trial;quotient|=1<<(7-i);}return {i,trial,take,remainder,quotient};});}
export function translate(va,table,tlb={}){const vpn=Math.floor(va/256),offset=va%256;if(Object.hasOwn(tlb,vpn))return {vpn,offset,hit:true,fault:false,frame:tlb[vpn],pa:tlb[vpn]*256+offset};const frame=table[vpn];return {vpn,offset,hit:false,fault:frame===null||frame===undefined,frame,pa:frame==null?null:frame*256+offset};}
export function cacheAccess(cache,address){const block=Math.floor(address/4),index=block%4,tag=Math.floor(block/4),hit=cache[index]===tag;const next=[...cache];next[index]=tag;return {cache:next,block,index,tag,offset:address%4,hit};}
const ops={LDI:1,LOAD:2,STORE:3,ADD:4,SUB:5,MUL:6,JNZ:7,OUT:8,HALT:15};
export const example='LDI R0, 7\nLDI R1, 5\nADD R0, R1\nSTORE R0, 128\nLOAD R2, 128\nOUT R2\nHALT';
export function assemble(text){const lines=text.split('\n').map(s=>s.split(';')[0].trim()).filter(Boolean);if(lines.length>64)throw Error('最多 64 条指令');return lines.map((line,i)=>{const parts=line.toUpperCase().replaceAll(',',' ').split(/\s+/),op=parts[0];if(!ops[op])throw Error(`第 ${i+1} 条：未知指令 ${op}`);const reg=s=>/^R[0-3]$/.test(s??'');const num=s=>s!==undefined&&/^(0X[0-9A-F]+|\d+)$/.test(s)&&Number(s)<=255;let r=0,arg=0;const count=op==='HALT'?1:op==='OUT'?2:3;if(parts.length!==count)throw Error(`第 ${i+1} 条：操作数数量错误`);if(op!=='HALT'){if(!reg(parts[1]))throw Error(`第 ${i+1} 条：寄存器必须为 R0–R3`);r=Number(parts[1][1]);}if(count===3){if(['ADD','SUB','MUL'].includes(op)){if(!reg(parts[2]))throw Error(`第 ${i+1} 条：需要寄存器操作数`);arg=Number(parts[2][1]);}else{if(!num(parts[2]))throw Error(`第 ${i+1} 条：立即数/地址须为 0–255`);arg=Number(parts[2]);}}if(op==='JNZ'&&(arg%2||arg>=lines.length*2))throw Error(`第 ${i+1} 条：跳转目标必须是程序内偶数字节地址`);return {op,r,arg,text:line,word:(ops[op]<<12)|(r<<10)|arg};});}
export function initial(program=assemble(example)){const mem=Array(256).fill(0);program.forEach((x,i)=>{mem[i*2]=x.word>>>8;mem[i*2+1]=x.word&255;});return {program,mem,regs:[0,0,0,0],pc:0,mar:0,mdr:0,ir:0,phase:0,clock:0,retired:0,halted:false,flags:add8(0,0),active:['pc'],flow:'pc-bus',note:'准备就绪。PC 指向第一条指令，点击单步开始。',output:[],current:null};}
export function tick(old){if(old.halted)return old;const s=structuredClone(old);s.clock++;const phases=[()=>{s.mar=s.pc;s.active=['pc','bus'];s.flow='pc-bus';s.note=`PC → MAR：将指令地址 ${hex(s.pc)} 放上地址总线。`;},()=>{if(s.mar>=255){s.halted=true;s.note='取指越界，机器停止。';return;}s.mdr=(s.mem[s.mar]<<8)|s.mem[s.mar+1];s.active=['memory','bus'];s.flow='memory-bus';s.note=`主存 → MDR：读取两个字节，得到指令 ${hex(s.mdr)}。`;},()=>{s.ir=s.mdr;s.pc+=2;s.active=['pc','control'];s.flow='bus-control';s.note=`MDR → IR，PC + 2 → PC。指令长度为 16 位。`;},()=>{const opcode=s.ir>>>12,op=Object.keys(ops).find(k=>ops[k]===opcode);if(!op){s.halted=true;s.note='非法操作码：机器停止。';return;}s.current={op,r:(s.ir>>>10)&3,arg:s.ir&255};s.active=['control','registers'];s.flow='control-registers';s.note=`译码：${op}，目标寄存器 R${s.current.r}，操作数字段 ${s.current.arg}。`;},()=>{const {op,r,arg}=s.current;if(['ADD','SUB','MUL'].includes(op)&&arg>3){s.halted=true;s.note='非法源寄存器：机器停止。';return;}s.active=['alu','registers'];s.flow='registers-alu';if(op==='LDI'){s.pending=arg;s.note=`立即数 ${arg} 送入内部数据通路。`;}else if(op==='LOAD'){s.mar=arg;s.pending=s.mem[arg];s.active=['memory','bus','registers'];s.flow='memory-bus';s.note=`读取 M[${hex(arg)}] = ${s.pending}。`;}else if(op==='STORE'){s.mar=arg;s.mdr=s.regs[r];s.active=['memory','bus','registers'];s.flow='registers-memory';s.note=`R${r} → MDR，准备向 ${hex(arg)} 写入 ${s.mdr}。`;}else if(op==='ADD'||op==='SUB'){s.flags=add8(s.regs[r],s.regs[arg],op==='SUB');s.pending=s.flags.value;s.note=`ALU：${s.regs[r]} ${op==='ADD'?'+':'−'} ${s.regs[arg]} = ${s.pending}（8 位结果）。`;}else if(op==='MUL'){const product=s.regs[r]*s.regs[arg];s.pending=product&255;s.flags={CF:+(product>255),OF:+(product>255),ZF:+(!s.pending),SF:s.pending>>>7};s.note=`乘积 ${product}，低 8 位 ${s.pending} 写回；高位丢弃以 CF/OF 指示。`;}else if(op==='JNZ'){s.note=`检测 R${r} = ${s.regs[r]}，${s.regs[r]?'将跳转至 '+hex(arg):'不跳转'}。`;s.active=['control','pc'];}else if(op==='OUT'){s.note=`准备把 R${r} = ${s.regs[r]} 送往输出接口。`;s.active=['io','bus'];s.flow='bus-io';}else{s.active=['control'];s.note='HALT：准备停止执行。';}},()=>{const {op,r,arg}=s.current;s.active=['registers'];s.flow='alu-registers';if(['LDI','LOAD','ADD','SUB','MUL'].includes(op))s.regs[r]=s.pending;if(op==='STORE'){s.mem[arg]=s.mdr;s.active=['memory'];}if(op==='JNZ'&&s.regs[r])s.pc=arg;if(op==='OUT'){s.output.push(s.regs[r]);s.active=['io'];}if(op==='HALT')s.halted=true;s.retired++;s.note=s.halted?'程序执行完毕。可以回退检查，也可以复位重新执行。':`${op} 完成，进入下一条指令。`; }];phases[s.phase]();s.phase=(s.phase+1)%6;return s;}
