import {advancedTrace} from './advanced.js?v=2.8.3';
import {text,escape,defs} from './textbook.js?v=2.8.3';
export function flowModel(page,p,f,i){let labels=[],active=0,steps=[],decision=-1,loop=false,branches=[];
if(f.kind){const trace=advancedTrace(page,p);steps=Array.from({length:Math.min(6,trace.length)},(_,j)=>Math.round(j*(trace.length-1)/(Math.min(6,trace.length)-1)));labels=steps.map(k=>trace[k].title.length>12?trace[k].title.slice(0,11)+"…":trace[k].title);active=steps.reduce((best,k,j)=>k<=i?j:best,0);}
else if(['multiplier','divider'].includes(page)){const mul=page==='multiplier',round=f.round;labels=mul?['初始化 M、Q、P','检测 Q₀ = 1？','P ← P + M','M 左移 / Q 右移','计数 +1，满 8 轮？','结束：读取 P']:['R 左移并移入 A 位','试减 R − B','试减 ≥ 0？','保留 / 恢复 R，写商','计数 +1，满 8 轮？','结束：读取 Q、R'];active=mul?f.phase===0?1:f.phase===1?2:3:f.phase===0?0:f.phase===1?1:3;steps=mul?[0,round*3,round*3+1,round*3+2,Math.min(23,round*3+2),23]:[round*3,round*3+1,round*3+2,round*3+2,Math.min(23,round*3+2),23];decision=mul?1:2;loop=true;branches=mul?['是：选通 ALU','否：保持 P']:['是：保留 R / 商 1','否：恢复 R / 商 0'];if(i===23)active=5;}
else if(page==='memory'){labels=['锁存地址','高位片选 / 低位选字','首字等待','输出数据拍','列计数 +1，满 4 拍？','完成'];steps=[0,1,3,4,5,8];active=i<1?0:i<3?1:i===3?2:i<8?3:5;decision=4;loop=true;branches=['是：结束','否：下一数据拍'];}
else if(page==='system'||page==='io'&&p.ioMode==='dma'){labels=['CPU 配置地址和计数','DREQ → HOLD','HLDA → DACK','IOR / MEMW 搬运','COUNT = 0？','释放总线 / 完成 IRQ'];steps=[0,2,4,6,9,10];active=i<2?0:i<4?1:i<6?2:i<10?3:5;decision=4;loop=true;branches=['是：释放总线','否：地址 +1，再传输'];}
else if(page==='io'){const poll=p.ioMode==='poll';labels=poll?['写控制命令','读取状态寄存器','READY = 1？','读取数据寄存器','CPU 写入主存','结束']:['发起 I/O 命令','CPU 执行其他指令','收到 IRQ？','保存现场并服务','CPU 读取数据','恢复现场'];steps=poll?[0,1,2,4,5,5]:[0,1,2,3,4,5];active=poll?[0,1,2,2,3,4][i]:i;decision=2;loop=true;branches=poll?['是：读取数据','否：继续查询']:['是：响应中断','否：继续执行'];}
else if(page==='cpu'){labels=['PC → MAR','主存 → MDR','MDR → IR / PC+2','译码生成控制信号','运算 / 访存 / 分支','写回 / 检查 HALT'];const base=Math.floor(Math.max(0,f.cpu.clock-1)/6)*6;steps=[1,2,3,4,5,6].map(n=>base+n);active=f.cpu.clock?((f.cpu.phase+5)%6):0;loop=true;branches=['HALT：停止','非 HALT：下一条'];}
else if(page==='disk'){labels=['分解目标 C / H / S','移动磁头：寻道','旋转等待目标扇区','选通磁头并传输','本次访问完成'];steps=[0,1,2,3,4];active=i;}
else if(page==='paging'){labels=['分离 VPN / 偏移','查 TLB：本例 Miss','查页表 V = 1？','页框号拼接偏移','物理访存'];steps=[0,1,2,3,4];active=i;decision=2;branches=['是：组成 PA','否：缺页，交 OS'];if(f.pf===null&&i>=2)active=2;}
else if(page==='adder'){labels=['输入 A、B、C₀=0','计算当前位 Sᵢ','计算下一位 Cᵢ₊₁','进位送高位 FA','到达最高位？','读取和与状态标志'];steps=[0,i,i,Math.min(7,i+1),7,7];active=i===7?5:2;decision=4;loop=true;branches=['是：生成 CF / OF','否：处理下一位'];}
else{labels=['输入 D / 设置 EN','等待 CLK 上升沿','EN = 1？','Q ← D','保持 Q'];steps=[0,1,1,1,3];active=i===0?0:i===1?p.enable?3:4:4;decision=2;branches=['是：采样','否：保持'];}
return {labels,active,steps,decision,loop,branches};}
function flowLines(label,maxUnits){
 const tokens=label.match(/[A-Za-z0-9_]+|[^A-Za-z0-9_]/gu)??[];const lines=[''];let used=0;
 for(const token of tokens){const width=[...token].reduce((n,c)=>n+(/[^\x00-\x7F]/.test(c)?1:.55),0);if(used+width>maxUnits&&lines.at(-1).trim()){lines.push('');used=0;}lines[lines.length-1]+=token;used+=width;}
 return lines.map(s=>s.trim()).filter(Boolean).slice(0,2).map((s,i)=>i===1&&lines.length>2?s+'…':s);
}
export function flowchartMarkup(page,p,f,i){const m=flowModel(page,p,f,i),n=m.labels.length,w=1000/n,cy=90;let shapes='',lines='';m.labels.forEach((label,j)=>{const x=j*w+12,cx=x+(w-24)/2,h=70,y=55,decision=j===m.decision||(['multiplier','divider'].includes(page)&&j===4);const geom=decision?`<path d="M${cx} ${y-6}L${x+w-24} ${cy}L${cx} ${y+h+6}L${x} ${cy}Z"/>`:`<rect x="${x}" y="${y}" width="${w-24}" height="${h}" rx="${j===0||j===n-1?20:4}"/>`;const chunks=flowLines(label,(w-42)/15);shapes+=`<g class="flow-node ${j===m.active?'hot':''}" data-step="${m.steps[j]}" role="button" tabindex="0" aria-label="跳到${escape(label)}">${geom}${chunks.map((s,k)=>text(cx,cy+5-(chunks.length-1)*13+k*26,s,'flow-text','middle')).join('')}</g>`;if(j<n-1)lines+=`<path d="M${x+w-24} ${cy}H${x+w}" class="tb-wire data" marker-end="url(#tb-data)"/>`;});if(m.loop){const polling=page==='io'&&p.ioMode!=='dma';const from=(polling?2:page==='cpu'?5:n-2)*w+w/2,to=(page==='memory'||page==='system'||page==='io'&&p.ioMode==='dma'?3:page==='cpu'||page==='divider'?0:1)*w+w/2;lines+=`<path d="M${from} 131V195H${to}V132" class="tb-wire control" marker-end="url(#tb-control)"/>${text((from+to)/2,184,(['multiplier','divider'].includes(page)?'未满 8 轮：继续':m.branches[1]??'继续下一轮'),'tb-small','middle')}`;}if(page==='multiplier'){lines+=`<path d="M${1.5*w} 49V17H${3.5*w}V49" class="tb-wire control" marker-end="url(#tb-control)"/>${text(2.5*w,12,'Q₀ = 0：保持 P，跳过加法','tb-small','middle')}`;}if(m.decision>=0){const x=m.decision*w+w/2;lines+=text(x,35,m.branches[0]??'是','tb-small','middle');if(!m.loop)lines+=`<path d="M${x} 131V195H${Math.min(950,x+250)}" class="tb-wire control" marker-end="url(#tb-control)"/>${text(x+10,177,m.branches[1],'tb-small')}`;}return `<svg class="flow-svg" viewBox="0 0 1000 230" aria-label="${page} 执行流程图">${defs}<rect width="1000" height="230" fill="#fafbf6"/>${lines}${shapes}${text(15,221,'点击流程节点定位步骤 · 高亮与原理图同步','tb-small')}</svg>`;}
