import {advancedCatalog,advancedDefaults,advancedTrace} from './advanced.js?v=2.8.3';
import {initial,tick,multiplySteps,divideSteps,add8,bits,hex} from './engine.js?v=2.8.3';
export const catalog={...advancedCatalog,system:['整机实验台','SYSTEM / HARDWARE','CPU、存储与外设之间，一次真实的数据旅程。'],memory:['存储器组织','MEMORY / ORGANIZATION','从存储单元到芯片组，看见容量如何扩展。'],disk:['磁盘机械结构','DISK / GEOMETRY','寻道、旋转与传输，分别发生在哪里。'],io:['外设接口与 DMA','I/O / DIRECT MEMORY ACCESS','沿着控制线与数据线，追踪总线所有权。'],cpu:['CPU 数据通路','CPU / DATAPATH','指令驱动控制信号，数据经过运算器并写回。'],multiplier:['移位加法乘法器','ARITHMETIC / MULTIPLY','把每一轮条件加法与移位，展开为空间中的数据轨道。'],divider:['恢复余数除法器','ARITHMETIC / DIVIDE','试减、判断、恢复与商位生成，逐轮观察。'],adder:['全加器与进位链','ARITHMETIC / ADDER','从最低位出发，跟踪逐级进位。'],paging:['页表与地址转换','MEMORY / VIRTUAL ADDRESS','虚拟页映射到物理页框，页内偏移保持不变。'],flipflop:['基础选学 · 触发器','LOGIC / STORAGE','只在有效时钟边沿采样，把输入保存为状态。']};
export const defaults=()=>({mode:'both',address:2,a:7,b:5,track:4,surface:2,sector:5,ioMode:'dma',va:530,d:1,enable:1,...advancedDefaults});
export function memoryLayout(mode){const lanes=mode==='word'?1:2,banks=mode==='bit'?1:2;return {lanes,banks,words:4*banks,width:4*lanes,chips:lanes*banks,capacityBits:16*lanes*banks};}
export function memoryRead(address,mode){const l=memoryLayout(mode),bank=Math.floor(address/4),word=address%4,value=(0x35+address*13)&((1<<l.width)-1);return {...l,bank,word,value,nibbles:Array.from({length:l.lanes},(_,i)=>(value>>i*4)&15)};}
export function diskKinematics(track,sector){const radius=.75+track*.235,L=4,dx=4,dz=1.7,distance=Math.hypot(dx,dz);const angle=Math.acos((distance**2+L**2-radius**2)/(2*L*distance))-Math.atan2(dz,dx);const x=dx-L*Math.cos(angle),z=dz+L*Math.sin(angle),bearing=Math.atan2(z,x);const rotation=((-bearing-(sector+.5)*Math.PI/6)%(2*Math.PI)+2*Math.PI)%(2*Math.PI);return {radius,angle,x,z,rotation};}
const make=(title,note,active=[],route=[],values={},extra={})=>({title,note,active,route,values,...extra});
export function total(page,p){if(advancedCatalog[page])return advancedTrace(page,p).length;return {system:12,memory:9,disk:5,io:p.ioMode==='dma'?12:6,cpu:42,multiplier:24,divider:24,adder:8,paging:5,flipflop:4}[page];}
export function frame(page,i,p,cpu){if(advancedCatalog[page])return advancedTrace(page,p)[i];if(page==='system'||page==='io')return ioFrame(i,p,page==='system');
if(page==='cpu'){const s=cpu??initial();return make(s.clock?['地址','读指令','锁存','译码','执行','写回'][(s.phase+5)%6]:'准备就绪',s.note,s.active.map(k=>({pc:'pc',control:'control',registers:'registers',alu:'alu',memory:'memory',bus:'bus',io:'io'}[k])),s.flow?.split('-').map(k=>({registers:'registers',control:'control',memory:'memory',bus:'bus',pc:'pc',alu:'alu',io:'io'}[k]))??[],{pc:hex(s.pc),ir:hex(s.ir),registers:s.regs.join(' / '),alu:s.pending??0,memory:s.mem[128],output:s.output.join(', ')||'—'}, {cpu:s});}
if(page==='memory'){const l=memoryLayout(p.mode),start=Math.min(p.address,l.words-1),bank=Math.floor(start/4),col=start%4;const read=memoryRead(start,p.mode);const beat=Math.min(3,Math.max(0,i-4)),address=bank*4+(col+beat)%4,r=memoryRead(address,p.mode),selected=Array.from({length:l.lanes},(_,lane)=>`chip-${bank}-${lane}`);const values={capacity:`${l.words} × ${l.width} bit`,address:i>=4?address:start,bank,word:i>=4?r.word:col,data:i>=4?r.value:read.value,beat:i<4?0:Math.min(4,beat+1),...Object.fromEntries(selected.map((id,lane)=>[id,i>=4?r.nibbles[lane]:read.nibbles[lane]]))};const titles=['地址送出','高位译码 / 片选','低位行列选择','首字等待','突发拍 1','突发拍 2','突发拍 3','突发拍 4','传输完成'];let note=['地址总线共享给所有芯片。高地址位选择存储组；同组芯片并行提供不同数据位。',`选择第 ${bank} 组，其他组的输出保持高阻。位扩展芯片共享同一个片选。`,`组内地址 ${col} 同时选择各芯片的同一字。每颗芯片给出 4 位，按位拼成 ${l.width} 位。`,'突发长度为 4：锁存起始列后，内部列计数器提供后续地址。这里是同步突发概念模型，省略 DRAM 的 PRE/ACT 等时序。',...Array.from({length:4},(_,k)=>`第 ${k+1} 拍：地址 ${bank*4+(col+k)%4}，数据 ${hex(memoryRead(bank*4+(col+k)%4,p.mode).value,2)}。同一 4 字边界内按序回绕，外部无需逐拍重新发列地址。`),'4 个数据拍结束。扩展改变位宽或深度；突发改变连续传输的组织方式。'][i];return make(titles[i],note,i<2?['address','decoder']:i<4?['decoder',...selected]:i<8?[...selected,'data']:['data'],i===0?['address','decoder']:i<4?['decoder',...selected]:i<8?[selected[0],'data']:[],values,{memory:r,beat,bank,word:i>=4?r.word:col,read:i>=4&&i<8,routes:i>=1&&i<4?selected.map(id=>['decoder',id]):i>=4&&i<8?selected.map(id=>[id,'data']):undefined});}
if(page==='disk'){const lba=(p.track*6+p.surface)*12+p.sector;return make(['选择目标 CHS','移动磁头 / 寻道','等待目标扇区旋转','磁头读取 / 传输','本次访问完成'][i],[`目标：柱面 ${p.track}，盘面 ${p.surface}，扇区 ${p.sector}。3 个盘片有 6 个数据盘面，每面 8 磁道、每道 12 扇区。`,'共用执行器联动所有磁头到目标半径；同半径的磁道集合构成柱面。','磁头停在目标磁道，盘片旋转，等待目标扇区到达选中的磁头下方。',`只选通盘面 ${p.surface} 的磁头。扇区数据经过磁盘控制器送出；其他磁头不同时读写。`,`教学 CHS 对应 LBA = (C × 6 + H) × 12 + S = ${lba}。现代磁盘通常向主机暴露 LBA；这里演示机械几何。`][i],i===1?['head']:i===2?['platter']:i===3?['head','controller']:['platter'],i===3?['head','controller']:[],{track:p.track,surface:p.surface,sector:p.sector,lba},{diskStage:i});}
if(page==='multiplier'||page==='divider'){const round=Math.floor(i/3),phase=i%3;if(page==='multiplier'){const row=multiplySteps(p.a,p.b)[round],before=round?multiplySteps(p.a,p.b)[round-1].acc:0;return make(['检查乘数位','条件加法','移位进入下一轮'][phase],[`第 ${round+1} 轮：检查 Q 的最低位 ${(p.b>>round)&1}。`,`部分积 ${before} ${row.bit?'+ '+row.part:'+ 0'} = ${row.acc}。${row.bit?'加法通路选通。':'跳过加法，保持部分积。'}`,`M 左移 1 位，Q 右移 1 位；已处理 ${round+1} 个乘数位。`][phase],phase===0?['quotient']:phase===1?['operand','alu','accumulator']:['operand','quotient'],phase===1&&row.bit?['operand','alu','accumulator']:phase===2?['quotient','shift']:[],{operand:p.a*2**(round+(phase===2?1:0)),quotient:p.b>>(round+(phase===2?1:0)),accumulator:phase===0?before:row.acc,round:round+1,bit:row.bit},{round,phase,width:16});}
const steps=divideSteps(p.a,p.b),row=steps[round],before=round?steps[round-1].remainder:0,shifted=before*2+((p.a>>(7-round))&1);return make(['移入被除数一位','试减除数','恢复 / 写入商位'][phase],[`余数左移并移入被除数第 ${7-round} 位：${shifted}。`,`试减 ${shifted} − ${p.b} = ${row.trial}。试减结果使用有符号的 9 位暂存器展示。`,`${row.take?'试减非负，保留结果，商位写 1。':'试减为负，恢复试减前余数，商位写 0。'}${round===7?`最终 ${p.a} = ${row.quotient} × ${p.b} + ${row.remainder}。`:''}`][phase],phase===0?['dividend','accumulator']:phase===1?['operand','alu']:['accumulator','quotient'],phase===0?['dividend','accumulator']:phase===1?['accumulator','alu']:['alu','accumulator','quotient'],{operand:p.b,dividend:p.a,accumulator:phase===0?shifted:phase===1?row.trial:row.remainder,quotient:phase===2?row.quotient:round?steps[round-1].quotient:0,round:round+1,bit:+row.take},{round,phase,width:9});}
if(page==='adder'){let carry=0,rows=[];for(let j=0;j<8;j++){let ai=p.a>>j&1,bi=p.b>>j&1,sum=ai+bi+carry;rows.push({ai,bi,carry,sum:sum&1,next:sum>>1});carry=sum>>1;}const r=rows[i],result=add8(p.a,p.b);return make(`第 ${i} 位全加器`,`A${i}=${r.ai}，B${i}=${r.bi}，输入进位 ${r.carry} → 和位 ${r.sum}，输出进位 ${r.next}。CF=${result.CF}，OF=${result.OF}。`,[`fa-${i}`],i<7?[`fa-${i}`,`fa-${i+1}`]:[],{a:p.a,b:p.b,result:result.value,...result},{rows,round:i});}
if(page==='paging'){let vpn=Math.floor(p.va/256),offset=p.va%256,table=[3,1,5,null],pf=table[vpn];return make(['拆分虚拟地址','查询 TLB','查询页表','组成物理地址','访问物理页框'][i],pf===null&&i>=2?'页表有效位为 0：缺页异常，不能继续组成物理地址。需操作系统调入页面。':[`VA=${p.va}，页号=${vpn}，偏移=${offset}。页大小为 256 B。`,'本例从空 TLB 开始；未命中后查页表，不等于缺页。',`页 ${vpn} 的有效映射是页框 ${pf}。`,`物理地址 = ${pf} × 256 + ${offset} = ${pf*256+offset}。`,`访问页框 ${pf} 的偏移 ${offset}；连续虚拟页不要求映射到连续物理页框。`][i],pf===null&&i>=2?[`vpage-${vpn}`]:i<2?['tlb']:i===2?[`vpage-${vpn}`]:[`pframe-${pf}`],pf!==null&&i>=3?[`vpage-${vpn}`,`pframe-${pf}`]:[],{va:p.va,vpn,offset,pa:pf===null?'缺页':pf*256+offset},{vpn,pf});}
return make(['输入准备','时钟上升沿','高电平保持','时钟下降沿'][i],`D=${p.d}，EN=${p.enable}。${i===1?'有效上升沿采样输入。':'非采样边沿保持 Q。'}理想数字模型，不模拟建立/保持时间。`,i===1?['d','q']:['clock'],i===1&&p.enable?['d','q']:[],{d:p.d,q:i>=1&&p.enable?p.d:0,clock:i===1||i===2?1:0});}
function ioFrame(i,p,system){const mode=system?'dma':p.ioMode;if(mode==='dma'){const transferred=Math.max(0,Math.min(4,i-5));const titles=['CPU 配置 DMA','外设准备数据','外设请求 DREQ','DMA 请求总线 HOLD','CPU 授权 HLDA','DMA 应答 DACK','传输字节 1','传输字节 2','传输字节 3','传输字节 4','DMA 释放总线 / IRQ','CPU 恢复执行'];const route=[['cpu','dma'],['disk','io'],['io','dma'],['dma','cpu'],['cpu','dma'],['dma','io'],['io','memory'],['io','memory'],['io','memory'],['io','memory'],['dma','cpu'],['cpu','memory']][i];return make(titles[i],[`写入 DMA 目的地址 128、计数 4 与读外设模式。`,'磁盘控制器将数据放入接口数据缓冲寄存器。','DREQ 控制线请求 DMA 服务，尚未占有系统总线。','HOLD 请求总线所有权，等待 CPU 完成当前总线事务。','CPU 发出 HLDA，暂时让出地址/数据/控制线。','DACK 选择外设接口，准备 I/O 读与主存写。',...Array.from({length:4},(_,n)=>`IOR + MEMW 有效，数据 ${hex(0x41+n,2)} 经数据线写入 M[${128+n}]。地址加一，计数减一。`),'计数变为零，DMA 释放总线，发送完成中断。','CPU 处理中断并继续工作。此场景为 DMA 块传输教学模型，与 CPU 汇编实验分开计时。'][i],route,route,{address:128+transferred,count:4-transferred,data:i>=6&&i<=9?hex(0x41+i-6,2):'—',owner:i>=5&&i<=9?'DMA':'CPU',memory:Array.from({length:4},(_,n)=>n<transferred?hex(0x41+n,2):'—').join(' '),signal:['WR','READY','DREQ','HOLD','HLDA','DACK','IOR + MEMW','IOR + MEMW','IOR + MEMW','IOR + MEMW','IRQ','ACK'][i]},{signalType:i>=6&&i<=9?'data':i===0?'address':'control',transferred});}
const interrupt=mode==='interrupt';const titles=interrupt?['发起外设命令','CPU 执行其他指令','设备发出 IRQ','保存现场 / 进入服务','读取数据寄存器','恢复现场']:['写控制寄存器','读状态寄存器','检测 READY=0','再次读取 READY=1','读数据寄存器','写入主存'];const routes=[['cpu','controlreg'],['statusreg','cpu'],['io','cpu'],['statusreg','cpu'],['datareg','cpu'],['cpu','memory']];return make(titles[i],`${interrupt?'程序中断':'程序查询'}。接口地址 0xF0：读选状态寄存器，写选控制寄存器；0xF1：读写数据寄存器。地址相同不代表同一寄存器，读写控制线参与译码。${i===4?'当前 RD 有效，数据缓冲送往 CPU。':''}`,routes[i],routes[i],{address:i===4?'0xF1':'0xF0',data:i>=4?'0x41':'—',owner:'CPU',count:'—',signal:i===0?'WR':i===4?'RD':interrupt&&i===2?'IRQ':'RD'},{signalType:i===4?'data':'control'});}
