import {createLearningIndex,searchLearning,decodeProgress,learningResources} from './learning-index.js?v=2.8.3';
import {renderProse} from './prose.js?v=2.8.3';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
export class LearningNavigator{
 constructor(host,{locate,experiment}){this.host=host;this.locate=locate;this.experiment=experiment;this.entries=createLearningIndex();this.storageKey='microcosm.learning.v1';try{this.completed=new Set(decodeProgress(localStorage.getItem(this.storageKey),this.entries));}catch{this.completed=new Set();}
 host.innerHTML=`<details class="learning-search" open><summary>知识导航与学习进度 <span id="learning-progress"></span></summary><div class="learning-filters"><label>搜索知识点<input id="learning-query" type="search" placeholder="例如：流水线 LOAD-use"></label><label>章节<select id="learning-chapter"><option value="">全部章节</option>${[...new Set(this.entries.map(e=>e.chapter))].map(c=>`<option>${esc(c)}</option>`).join('')}</select></label><label><input id="learning-priority" type="checkbox">只看重点</label><label><input id="learning-completed" type="checkbox">只看已学</label><button id="learning-chapter-focus">聚焦章节</button></div><p id="learning-result-count" role="status"></p><div id="learning-results" class="learning-results"></div><button id="learning-more" hidden>显示更多结果</button><div id="learning-selection" class="learning-selection"></div></details>`;
 this.limit=30;for(const id of ['learning-query','learning-chapter','learning-priority','learning-completed'])host.querySelector('#'+id).addEventListener('input',()=>{this.limit=30;this.render();});
 host.querySelector('#learning-more').onclick=()=>{this.limit+=30;this.render();};host.querySelector('#learning-chapter-focus').onclick=()=>{const chapter=this.value('learning-chapter');const node=this.entries.find(e=>e.title===chapter);if(node)this.select(node.key,true);};this.render();}
 value(id){return this.host.querySelector('#'+id).value;}
 render(){const matches=searchLearning(this.entries,{query:this.value('learning-query'),chapter:this.value('learning-chapter'),priorityOnly:this.host.querySelector('#learning-priority').checked,completedOnly:this.host.querySelector('#learning-completed').checked,completed:[...this.completed]});this.host.querySelector('#learning-progress').textContent=`已学 ${this.completed.size} / ${this.entries.length}`;this.host.querySelector('#learning-result-count').textContent=matches.length?`${matches.length} 个结果 · 点击定位并查看学习资源`:'没有匹配结果，请调整关键词或筛选条件。';this.host.querySelector('#learning-results').innerHTML=matches.slice(0,this.limit).map(e=>`<button data-learning="${e.key}" class="${this.selected===e.key?'selected':''}"><span>${this.completed.has(e.key)?'✓ ':''}${e.priority?'★ ':''}${esc(e.title)}</span><small>${esc(e.path.slice(0,-1).join(' › '))}</small></button>`).join('');this.host.querySelector('#learning-more').hidden=matches.length<=this.limit;this.host.querySelector('#learning-chapter-focus').disabled=!this.value('learning-chapter');this.host.querySelectorAll('[data-learning]').forEach(b=>b.onclick=()=>this.select(b.dataset.learning,true));}
 select(key,jump=false){const entry=this.entries.find(e=>e.key===key);if(!entry)return;this.selected=key;const resources=learningResources(this.entries,key);this.host.querySelector('#learning-selection').innerHTML=`<p class="learning-path">${esc(entry.path.join(' › '))}</p><div class="learning-actions"><button id="learning-mark">${this.completed.has(key)?'撤销已学':'标记已学'}</button><button id="learning-locate">在导图中定位</button></div><div class="prose">${renderProse('### '+entry.title+'\n\n'+(resources.notes.length?resources.notes.slice(0,12).map(e=>'- '+e.title).join('\n'):entry.title)+(resources.notes.length>12?'\n\n其余知识请逐层展开查看。':'')+'\n\n**例题**\n\n'+(resources.examples.length?resources.examples.map(e=>'- '+e.title).join('\n'):'本知识点暂无独立例题。'))}</div><div class="learning-actions">${resources.experiments.map(e=>`<button data-experiment="${e.link}">${esc(e.title)}</button>`).join('')||'<span>当前仅有知识讲解，暂无对应仿真。</span>'}</div><p class="muted">错题入口将在练习模块完成后启用；当前不产生虚构学习记录。</p><p id="learning-save-status" role="status"></p>`;
 this.host.querySelector('#learning-mark').onclick=()=>{this.completed.has(key)?this.completed.delete(key):this.completed.add(key);let saved=true;try{localStorage.setItem(this.storageKey,JSON.stringify({version:1,completed:[...this.completed]}));}catch{saved=false;}this.select(key);if(!saved)this.host.querySelector('#learning-save-status').textContent='浏览器不允许保存，进度仅保留在本次页面中。';};this.host.querySelector('#learning-locate').onclick=()=>this.locate(key);this.host.querySelectorAll('[data-experiment]').forEach(b=>b.onclick=()=>this.experiment(b.dataset.experiment));this.render();if(jump)this.locate(key);}
}
