import {ancestorKeys} from './learning-index.js?v=2.8.3';
import {knowledgeMapMarkup,knowledgeTreeLayout} from './knowledge-map.js?v=2.8.3';
import {renderArithmetic} from './arithmetic-view.js?v=2.8.3';
import {schematicMarkup} from './textbook.js?v=2.8.3';
import {diskKinematics} from './labs.js?v=2.8.3';
export class Schematic{
constructor(host,onSelect,onInspect=()=>{},onTrace=()=>{}){this.onTrace=onTrace;this.onInspect=onInspect;this.host=host;this.onSelect=onSelect;this.scale=1;this.tx=this.ty=0;host.innerHTML='<svg class="schematic textbook" viewBox="0 0 1000 720" aria-label="教材式硬件原理图"><g class="pan-layer"></g></svg>';this.svg=host.querySelector('svg');this.layer=host.querySelector('g');this.mapTrail=document.createElement('div');this.mapTrail.className='map-trail hidden';host.append(this.mapTrail);this.svg.addEventListener('wheel',e=>{e.preventDefault();this.zoom(e.deltaY>0?1.1:.9);},{passive:false});let start;this.svg.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();start={x:e.clientX,y:e.clientY,tx:this.tx,ty:this.ty};this.svg.setPointerCapture(e.pointerId);};this.svg.onpointermove=e=>{if(!start)return;const ratio=1/Math.min(this.svg.clientWidth/this.vw,this.svg.clientHeight/this.vh);this.tx=start.tx+(e.clientX-start.x)*ratio;this.ty=start.ty+(e.clientY-start.y)*ratio;this.transform();};this.svg.onpointerup=e=>{if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)<5){const el=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-link],[data-focus],[data-expand],[data-inspect],[data-register],[data-trace]');if(el?.dataset.register||el?.dataset.trace)this.onTrace(el.dataset.register??el.dataset.trace);else if(el?.dataset.link)this.onSelect(el.dataset.link);else if(el?.dataset.focus)this.focusChapter(Number(el.dataset.focus));else if(el?.dataset.expand)this.expandBranch(el.dataset.expand);else if(el?.dataset.inspect)this.onInspect(el.dataset.inspect);}start=null;};this.svg.onpointercancel=()=>start=null;this.svg.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();if(e.target.dataset.register||e.target.dataset.trace)this.onTrace(e.target.dataset.register??e.target.dataset.trace);else if(e.target.dataset.link)this.onSelect(e.target.dataset.link);else if(e.target.dataset.focus)this.focusChapter(Number(e.target.dataset.focus));else if(e.target.dataset.expand)this.expandBranch(e.target.dataset.expand);else if(e.target.dataset.inspect)this.onInspect(e.target.dataset.inspect);}};}
focusNode(key){this.expanded??=new Set(['0','1','2','3','4','5','6']);ancestorKeys(key).forEach(k=>this.expanded.add(k));this.setFrame(this.f);const n=knowledgeTreeLayout(this.expanded).nodes.find(n=>n.key===key);if(n){this.focusRegion(n.x+n.side*230,n.y,Math.min(700,this.host.clientWidth/.8),Math.min(600,this.host.clientHeight/.8));this.layer.querySelector(`[data-node="${key}"]`)?.classList.add('learning-selected');this.mapTrail.textContent=n.source.title;}}
expandBranch(key){this.onInspect(key);this.expanded??=new Set(['0','1','2','3','4','5','6']);if(this.expanded.has(key))this.expanded.delete(key);else this.expanded.add(key);this.setFrame(this.f);const n=knowledgeTreeLayout(this.expanded).nodes.find(n=>n.key===key);if(n){const narrow=this.host.clientWidth<900;this.focusRegion(n.x+n.side*(n.open?(narrow?770:470):230),n.y,narrow?this.host.clientWidth/.8:(n.open?1100:650),narrow?this.host.clientHeight/.8:Math.min(900,Math.max(400,n.height+80)));const layout=knowledgeTreeLayout(this.expanded);this.mapTrail.textContent=layout.nodes.filter(a=>key===a.key||key.startsWith(a.key+'-')).sort((a,b)=>a.depth-b.depth).map(a=>a.source.title).join(' › ');}}

focusRegion(x,y,w,h){this.scale=Math.min(this.host.clientWidth/w,this.host.clientHeight/h)/Math.min(this.host.clientWidth/this.vw,this.host.clientHeight/this.vh);this.tx=(this.vw/2-x)*this.scale;this.ty=(this.vh/2-y)*this.scale;this.transform();}
focusChapter(i){const c=knowledgeTreeLayout(this.expanded).chapterNodes[i];this.focusRegion(c.x+c.side*470,c.y,1100,Math.max(500,c.height+100));}
transform(){this.layer.setAttribute('transform',`translate(${this.vw/2+this.tx} ${this.vh/2+this.ty}) scale(${this.scale}) translate(${-this.vw/2} ${-this.vh/2})`);}
zoom(f){this.scale=Math.max(.5,Math.min(this.page==='system'?4/Math.min(this.host.clientWidth/this.vw,this.host.clientHeight/this.vh):4,this.scale/f));this.transform();}
resetCamera(){if(this.mapTrail)this.mapTrail.textContent='点击＋逐层展开 · 拖动查看相邻分支';this.scale=1;this.tx=this.ty=0;this.transform();}
build(page,p){this.page=page;this.mapTrail.classList.toggle('hidden',page!=='system');this.mapTrail.textContent='点击＋逐层展开 · 拖动查看相邻分支';this.vw=page==='system'?knowledgeTreeLayout(this.expanded).width:1000;this.vh=page==='system'?knowledgeTreeLayout(this.expanded).height:['isa','control','pipeline','interrupts','adder','multiplier','divider'].includes(page)?820:720;this.svg.setAttribute('viewBox',`0 0 ${this.vw} ${this.vh}`);this.p=p;this.resetCamera();}
setFrame(f){this.f=f;if(this.page==='system'){this.vw=knowledgeTreeLayout(this.expanded).width;this.vh=knowledgeTreeLayout(this.expanded).height;this.svg.setAttribute('viewBox',`0 0 ${this.vw} ${this.vh}`);this.layer.innerHTML=knowledgeMapMarkup(this.expanded);}else this.layer.innerHTML=schematicMarkup(this.page,this.p,f);this.paths=[...this.layer.querySelectorAll('.signal-group')].map(g=>({path:g.querySelector('path'),packet:g.querySelector('circle')}));this.transform();}
render(t,labels=true){if(['adder','multiplier','divider'].includes(this.page))renderArithmetic(this.layer,t);this.svg.classList.toggle('hide-callouts',!labels);for(const {path,packet} of this.paths){const point=path.getPointAtLength(t*path.getTotalLength());packet.setAttribute('cx',point.x);packet.setAttribute('cy',point.y);}if(this.page==='disk'){const k=diskKinematics(this.p.track,this.p.sector),stage=this.f.diskStage,rot=stage<2?0:stage===2?k.rotation*t:k.rotation;this.layer.querySelector('#disk-rotor')?.setAttribute('transform',`rotate(${-rot*180/Math.PI} 260 280)`);const r=54+this.p.track*10,ratio=stage===0?0:stage===1?t:1,x=415+(260+k.x/k.radius*r-415)*ratio,y=430+(280+k.z/k.radius*r-430)*ratio;this.layer.querySelector('#disk-head-path')?.setAttribute('d',`M455 460L${x} ${y}`);}}
dispose(){this.host.replaceChildren();}}
