import {arithmeticMotion} from './arithmetic-view.js?v=2.8.3';
const names={alu:'算术逻辑单元 ALU',control:'控制器',bus:'系统总线',mar:'地址寄存器 MAR',mdr:'数据寄存器 MDR',decoder:'译码器',a:'输入A',b:'输入B',result:'和S',operand:'M / B',accumulator:'P / R',quotient:'Q',dividend:'被除数A',pc:'PC',ir:'IR',registers:'寄存器',memory:'主存',data:'数据',signal:'控制信号',signals:'控制字',address:'地址',count:'剩余计数',EA:'有效地址',R0:'R0',SP:'栈指针',IF:'中断允许',MASK:'屏蔽',pa:'物理地址',vpn:'虚页号',offset:'页内偏移',q:'Q',d:'D',clock:'时钟'};
export function stepTrace(page,p,f,previous){
 const arithmetic=['adder','multiplier','divider'].includes(page),motion=arithmetic?arithmeticMotion(page,p,f):null;
 const route=(f.routes?.flat()??f.route??[]).filter(Boolean),source=route.length?(names[route[0]]??route[0]):'本实验输入 / 上一步状态',destination=route.length?(names[route.at(-1)]??route.at(-1)):'本步骤状态';
 const rows=motion?motion.rows.map(r=>({key:r.id,name:r.name,before:r.before,after:r.after,width:r.n,selected:r.selected,action:r.shift?`${r.shift<0?'左移':'右移'}1位，移入${r.fill??0}`:r.before===r.after?'保持数值；按高亮选择操作位':'接收本步骤写回值'})):Object.entries(f.values).filter(([key])=>!key.startsWith('chip-')).map(([key,value])=>({key,name:names[key]??key,before:previous?.values[key]??value,after:value,action:previous&&previous.values[key]!==value?'当前步骤更新':'本步骤保持 / 显示约定值'}));
 for(const signal of f.active??[])if(!rows.some(r=>r.key===signal))rows.push({key:signal,name:`控制/活动：${names[signal]??signal}`,before:previous?.active?.includes(signal)?'有效':'未激活',after:'有效',action:'此部件在当前教学步骤被选通；活动高亮不是所有电气控制线的逐位模型'});
 const arithmeticPath=page==='divider'?(f.phase===0?['余数 R 与被除数 A 的当前位','R：左移并移入被除数位']:f.phase===1?['余数 R 与除数 B','R：保存9位试减结果']:['R 的试减符号与除数 B','R：保留或恢复余数；Q：写入当前商位']):page==='multiplier'?(f.phase===0?['乘数 Q 的最低位 Q₀','控制器：决定累加或跳过']:f.phase===1?['部分积 P 与移位后的被乘数 M','P：累加结果；Q₀=0时保持']:['被乘数 M 与乘数 Q','M：左移补0；Q：右移补0']):null;
 return {title:f.title,mode:arithmetic?'当前操作前 → 当前操作后':'上一教学步骤快照 → 当前步骤快照',operation:motion?.operation??f.operation??f.note,explanation:f.note,result:motion?.result??'对照当前步骤的状态与控制信号。',source:page==='adder'?'A当前位、B当前位与低位进位C':arithmeticPath?.[0]??source,destination:page==='adder'?'和位S与高位进位C':arithmeticPath?.[1]??destination,route,rows,signals:[...new Set([...(f.active??[]),...(f.values.signals?String(f.values.signals).split(',').map(s=>s.trim()):[]),...(f.values.signal?[f.values.signal]:[])])],initial:!previous};
}
export function resolveTraceKey(key,trace){const aliases={result:'sum',alu:'accumulator',registers:'R0',mar:'EA',mdr:'operand',stack:'SP',pc:'pc',datareg:'data',controlreg:'signal',statusreg:'signal'};return trace.rows.find(r=>r.key===key)?.key??trace.rows.find(r=>r.key===aliases[key])?.key??null;}
